<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var string $graphqlEndpoint Magento default Graphql Endpoint */
$graphqlEndpoint =  $block->getBaseUrl() . "graphql";
?>
<div id="root" class="playgroundIn">
</div>
<script>
     const root = document.getElementById('root');
     GraphQLPlayground.init(root, {
         "endpoint": "<?= $graphqlEndpoint ?>",
         "canSaveConfig": true
     })
</script>
