<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\GraphQlPlayground\ViewModel\GraphQlFrontName;
// @codingStandardsIgnoreFile

/** @var string $graphQlFrontName */
$graphQlFrontName = $block->getFrontNameViewModel()->getGraphqlFrontName();
/** @var string $graphqlEndpoint Magento default Graphql Endpoint */
$graphqlEndpoint =  $block->getBaseUrl() . $graphQlFrontName;
?>
<div id="root" class="playgroundIn">
</div>
<script>
     var root = document.getElementById('root');
     GraphQLPlayground.init(root, {
         "endpoint": "<?= $graphqlEndpoint ?>",
         "canSaveConfig": true
     })
</script>
